from metadrive.component.map.base_map import BaseMap
from metadrive.component.map.pg_map import MapGenerateMethod
from metadrive.component.navigation_module.node_network_navigation import NodeNetworkNavigation
from metadrive.component.pgblock.first_block import FirstPGBlock
from metadrive.policy.env_input_policy import EnvInputPolicy

LEADER = "leader"
FOLLOWER_1 = "follower_1"
FOLLOWER_2 = "follower_2"
CUT_IN_VEHICLE = "cut_in_vehicle"

PLATOON_AGENT_IDS = (LEADER, FOLLOWER_1, FOLLOWER_2, CUT_IN_VEHICLE)

PLATOON_ENV_DEFAULT_CONFIG = dict(
    is_multi_agent=True,
    num_agents=4,
    allow_respawn=False,
    force_seed_spawn_manager=False,
    random_agent_model=False,
    crash_done=True,
    out_of_road_done=True,
    delay_done=0,
    horizon=350,
    start_seed=0,
    num_scenarios=1,
    map="S",
    random_lane_width=False,
    random_lane_num=False,
    random_spawn_lane_index=False,
    traffic_density=0.0,
    use_render=False,
    truncate_as_terminate=False,
    agent_policy=EnvInputPolicy,
    prefer_track_agent=LEADER,
    vehicle_config=dict(
        vehicle_model="default",
        navigation_module=NodeNetworkNavigation,
        show_navi_mark=False,
        show_dest_mark=False,
        show_line_to_dest=False,
        show_line_to_navi_mark=False,
        show_navigation_arrow=False,
        random_color=False,
        lidar=dict(num_lasers=0, distance=0, num_others=0),
        side_detector=dict(num_lasers=0, distance=0),
        lane_line_detector=dict(num_lasers=0, distance=0),
        show_lidar=False,
        show_side_detector=False,
        show_lane_line_detector=False,
    ),
    map_config=dict(
        type=MapGenerateMethod.BIG_BLOCK_SEQUENCE,
        config="S",
        lane_width=3.5,
        lane_num=2,
        exit_length=180,
        start_position=[0, 0],
    ),
    platoon=dict(
        observation_distance=80.0,
        max_speed_km_h=60.0,
        completion_lateral_threshold=0.35,
        completion_hold_steps=25,
        platoon_lane_index=0,
        cut_in_lane_index=1,
        spawn_road=(FirstPGBlock.NODE_2, FirstPGBlock.NODE_3),
        initial_longitudinal=12.0,
        inter_vehicle_spacing=20.0,
        initial_speed_km_h=32.0,
        leader_target_speed_km_h=36.0,
        follower_target_speed_km_h=36.0,
        cut_in_target_speed_km_h=42.0,
        desired_gap=18.0,
        external_control_agents=[],
        reward=dict(
            crash_penalty=10.0,
            out_of_road_penalty=10.0,
            gap_weight=0.08,
            speed_weight=0.04,
            lane_weight=0.05,
            cut_in_completion_bonus=3.0,
        ),
        leader_controller=dict(
            speed_kp=0.18,
            speed_ki=0.002,
            speed_kd=0.0,
            steer_heading_kp=1.7,
            steer_heading_ki=0.01,
            steer_heading_kd=3.5,
            steer_lateral_kp=0.3,
            steer_lateral_ki=0.002,
            steer_lateral_kd=0.05,
        ),
        follower_controller=dict(
            speed_kp=0.22,
            speed_ki=0.002,
            speed_kd=0.02,
            steer_heading_kp=1.7,
            steer_heading_ki=0.01,
            steer_heading_kd=3.5,
            steer_lateral_kp=0.3,
            steer_lateral_ki=0.002,
            steer_lateral_kd=0.05,
            gap_gain=0.45,
            max_gap_correction_km_h=10.0,
        ),
        cut_in_controller=dict(
            speed_kp=0.2,
            speed_ki=0.002,
            speed_kd=0.01,
            steer_heading_kp=1.7,
            steer_heading_ki=0.01,
            steer_heading_kd=3.5,
            steer_lateral_kp=0.3,
            steer_lateral_ki=0.002,
            steer_lateral_kd=0.05,
            trigger_step=35,
            trigger_min_longitudinal=28.0,
            min_front_gap=8.0,
            min_back_gap=6.0,
        ),
    ),
    visualization=dict(
        enable_render=False,
        enable_traj_vis=True,
        enable_debug_text=True,
        enable_terminal_log=True,
        save_video=False,
        save_frames=False,
        save_plot=False,
        output_dir="metadrive/platoon_env/outputs",
        film_size=(900, 900),
        screen_size=(900, 900),
        camera_position=(55, 0),
        num_stack=80,
        history_smooth=1,
        log_every=1,
        focus_on_cut_in=True,
        padding_front=35.0,
        padding_back=25.0,
    ),
)
